version: '3'
services:
  mock_server:
    image: flowwherecat/jsonserver:2.0
    container_name: chatbot_api
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    working_dir: /mock
    command: json-server --host 0.0.0.0 --id question_id -i user_open_id -i users_id   db.json --routes routes.json
  redis:
    container_name: chatbot_redis
    image: redis:5.0-rc4
    ports:
     - "6379:6379"
#    volumes:
#     - ./redis/data:/data
#     - ./redis/redis.config:/usr/local/etc/redis/redis.conf
  jupyter-tutorial:
    build: .
    container_name: chatbot_jupyter
    ports:
      - "8888:8888"
    command: start-notebook.sh --NotebookApp.token=''
    volumes:
     - ./code:/home/jovyan/work
  ngrok-external-dns:
    image: wernight/ngrok
    depends_on: 
      - jupyter-tutorial
    container_name: chatbot_ngrok
    ports:
      - "4040:4040"
    command: ngrok http chatbot_jupyter:5000
