version: '3'
services:
  mockapi:
    build: 
      context: ./dockerfile
      dockerfile: dockerfile-mockapi 
    container_name: chatbot_mockapi
    ports:
            - "5005:5005"
    command: python /home/mockapi/mockAPIserver.py
    volumes:
     - ./mockapi:/home/mockapi
  redis:
    build: 
      context: ./dockerfile
      dockerfile: dockerfile-redis
    container_name: chatbot_redis
    ports:
     - "6379:6379"
    volumes:
     - ./redis/data:/data
#     - ./redis/redis.config:/usr/local/etc/redis/redis.conf
  jupyter-tutorial:
    build: 
      context: ./dockerfile
      dockerfile: dockerfile-jupyter
    container_name: chatbot_jupyter
    depends_on: 
      - mockapi
      - redis
    ports:
      - "8888:8888"
      - "5000:5000"
    command: start-notebook.sh --NotebookApp.token=''
    volumes:
     - ./code:/home/jovyan/work
  ngrok-external-dns:
    build: 
      context: ./dockerfile
      dockerfile: dockerfile-ngrok
    container_name: chatbot_ngrok
    depends_on: 
      - jupyter-tutorial
    ports:
      - "4040:4040"
    command: ngrok http chatbot_jupyter:5000
