#指定基底文件為jupyter/base-notebook
FROM library/ubuntu
#安裝flask 0.12, request, line-bot-sdk
RUN apt-get install python-pip python-dev build-essential 
RUN pip install --upgrade pip 
RUN pip install --upgrade virtualenv 
RUN pip install Flask==0.12 requests line-bot-sdk redis
